### ISSUE TITLE
Adds recyclers to Cargo Ship has error

### ISSUE THREAD

**Issue by 2869949486** [WheteThunger/MonumentAddons#44]
when i use "mainstall MonumentsRecycler" command , The Recycler on the Cargo Ship is invisible
![Z F86OSCE8WNVVH TEGIZC](https://user-images.githubusercontent.com/70771089/202912811-7f2e4616-65d8-4ebf-b291-72ef36eab357.png)
![UU7CSVM0Z1 Z NLQ(I8S`S4](https://user-images.githubusercontent.com/70771089/202912814-58f22154-3907-44d9-83a9-277a9a175082.png)

**Comment by WheteThunger** [comment]
This is also an issue with the Monuments Recycler plugin. The recycler is still functional. This display issue not easily fixable because it's a vanilla client side issue that causes it to appear invisible. This profile only exists for parity. I don't plan on trying to fix this because it would not be worth the time.

**Comment by WheteThunger** [comment]
Closing as not planned.
